services:
  mongodb:
    container_name: mongodb
    image: mongo:5
    hostname: mongo
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_ADMIN
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_ADMIN_PWD
      - MONGO_INITDB_DATABASE=$DATABASE_NAME
      - MONGO_INITDB_USERNAME=$DATABASE_USER
      - MONGO_INITDB_PASSWORD=$DATABASE_USER_PWD
    volumes:
      - ./addons/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - dbdata:/data/db
    restart: unless-stopped
    networks:
      - express-network
networks:
  express-network:
    driver: bridge
volumes:
  dbdata:
