services:
  mongodb:
    container_name: mongodb
    image: mongo:6
    hostname: mongo
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - dbdata:/data/db
    restart: unless-stopped
    networks:
      - express-network
networks:
  express-network:
    driver: bridge
volumes:
  dbdata:
